### ISSUE TITLE
Conversations

### ISSUE THREAD

**Issue by alangecker** [yunity/foodsaving-frontend#151]
## ToDo's
- [ ] completing #191
- [ ] route `/conversation/with/:userId` for viewing/creating private conversations
- [ ] route `/conversation/new?participants=1,42,1337` for creating a new multichat
- [ ] participants selector
- [ ] 'Send Message' buttons on profil pages and pickup dates
- [ ] profil pictures

## Open Questions
- how to handle a conversation group, which got started for a specific pickup date, and somebody joins this date? (lower priority, but should be considered)

**Comment by alangecker** [comment]
some progress.... ;)
![conversations](https://cloud.githubusercontent.com/assets/10246027/21027611/db5cd024-bd91-11e6-87e0-443b33f30ba0.png)

**Comment by tiltec** [comment]
The backend needs to following changes:

- add participants to multichat
- leave multichat

Furthermore, the user should only be able to add participants that share a group with him.

**Comment by tiltec** [comment]
We postponed the development of chat/conversations in our last development meeting. We had the idea of integrating an already existing chat system later (maybe Matrix/Riot), maybe something else.

**Comment by tiltec** [comment]
Removing conversations in the backend? @alangecker 
https://github.com/yunity/foodsaving-backend/issues/254
